name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Build Pilot DB
        run: go build -v pilot-db/*
      - name: Test Pilot DB
        run: go test -v pilot-db/*
      - name: Build Pilot HTTP
        run: go build -v pilot-http/*
      - name: Test Pilot HTTP
        run: go test -v pilot-http/*
      - name: Build Pilot JSON
        run: go build -v pilot-json/*
      - name: Test Pilot JSON
        run: go test -v pilot-json/*

